name: voting_dapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.0
  http: ^1.6.0
  wallet_connect_v2: ^1.0.9
  web3dart: ^2.5.3
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  bloc_test: ^10.0.0
  json_serializable: ^6.11.2


flutter:
  uses-material-design: true
  assets:
    - assets/abi/ballot.json
